In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensors

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8847, 0.9874, 0.0492, 0.2459],
        [0.3062, 0.7740, 0.6991, 0.3059],
        [0.3095, 0.5643, 0.9657, 0.7420]])

In [17]:
# image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [18]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of tensors and tensors-like

In [20]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
one_to_hundred = torch.arange(start=0, end=100, step=5)
one_to_hundred

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [22]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
even_tensor = torch.arange(start=2, end=21, step=2)
even_tensor

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
even_zeros = torch.zeros_like(even_tensor)
even_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
even_tensor.ndim, even_zeros.ndim

(1, 1)

In [26]:
even_tensor.shape, even_zeros.shape

(torch.Size([10]), torch.Size([10]))

## Tensor datatypes

**Note:** Tensor datatypes is one of the big errors you will run into with PyTorch and deep learning:


1.   Tensor not right datatype `tensor.dtype`
2.   Tensor not right shape `tensor.shape`
3.   Tensor not on the right device `tensor.device`



In [27]:
# Default datatype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # float32, float16 (bit)
                               device=None, # cpu, gpu
                               requires_grad=False) # gradient descent
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Tensor operation

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication



In [30]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [31]:
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor - 10

tensor([-9, -8, -7])

In [33]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [34]:
tensor * 10

tensor([10, 20, 30])

## Matrix Multiplication

In [35]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [36]:
torch.matmul(MATRIX, MATRIX)

tensor([[121, 136],
        [153, 172]])

In [37]:
# 2x3 tensor
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
# 3x2 tensor
tensor2 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor1, tensor2

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [38]:
# 2x2 tensor
# matmul or mm
torch.mm(tensor1, tensor2)

tensor([[22, 28],
        [49, 64]])

### Transpose

In [39]:
tensor1 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor2 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

In [40]:
tensor2, tensor2.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 3, 5],
         [2, 4, 6]]))

In [41]:
tensor2.shape, tensor2.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [42]:
torch.mm(tensor1,tensor2.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

## min, max, mean, sum, and etc (tensor aggregation)

In [43]:
x = torch.arange(0,100,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [44]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [45]:
torch.max(x), x.max()

(tensor(95), tensor(95))

In [46]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(47.5000), tensor(47.5000))

In [47]:
torch.sum(x), x.sum()

(tensor(950), tensor(950))

## Positional min, max

In [48]:
x.argmin()

tensor(0)

In [49]:
x[0]

tensor(0)

In [50]:
x.argmax()

tensor(19)

In [51]:
x[19]

tensor(95)

## Changing the view of tensors
* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **Staking** - combine multiple tensors in one tensor
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [52]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# Reshaping
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
# View
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
z[:, 0] = 5.
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
# Staking
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [58]:
# Squeeze
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
# Permute
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


## Indxing

In [61]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [62]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
x[0][2]

tensor([7, 8, 9])

In [64]:
x[0][2][1], x[0, 2, 1]

(tensor(8), tensor(8))

In [65]:
# select all ":"
x[:,:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [66]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [67]:
# [from:to]
x[0 , 0:2 , 2]

tensor([3, 6])

## Tensors and NumPy
* numpy array to tensor `torch.from_numpy(array)`
* tensor to numpy array `torch.tensor.numpy()`

In [68]:
# numpy array to tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # float64
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [69]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
* **Random seed** `torch.manual_seed(RANDOM_SEED)`

In [70]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2673, 0.2725, 0.5558, 0.6313],
        [0.4321, 0.9353, 0.4619, 0.4154],
        [0.0057, 0.3261, 0.1955, 0.7902]])
tensor([[0.0361, 0.7226, 0.9984, 0.6397],
        [0.0152, 0.3140, 0.5101, 0.8697],
        [0.6183, 0.3176, 0.1086, 0.8142]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [71]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runing tensors and PyTorch objects on the GPUs
**options:**
1. Use Google colab
2. Use your own GPU
3. Use cloud computing

In [72]:
!nvidia-smi

Sun Nov 24 07:01:20 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [73]:
torch.cuda.is_available()

True

In [74]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [75]:
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

In [76]:
# using CPU
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [77]:
# device = "cuda" if torch.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensor back to the CPU

In [78]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [79]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')