In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensors

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6618, 0.6430, 0.6088, 0.0395],
        [0.9400, 0.0498, 0.7500, 0.3077],
        [0.4518, 0.9257, 0.0471, 0.0586]])

In [17]:
# image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [18]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## Range of tensors and tensors-like

In [20]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
one_to_hundred = torch.arange(start=0, end=100, step=5)
one_to_hundred

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [22]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
even_tensor = torch.arange(start=2, end=21, step=2)
even_tensor

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
even_zeros = torch.zeros_like(even_tensor)
even_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
even_tensor.ndim, even_zeros.ndim

(1, 1)

In [26]:
even_tensor.shape, even_zeros.shape

(torch.Size([10]), torch.Size([10]))

## Tensor datatypes

**Note:** Tensor datatypes is one of the big errors you will run into with PyTorch and deep learning:


1.   Tensor not right datatype `tensor.dtype`
2.   Tensor not right shape `tensor.shape`
3.   Tensor not on the right device `tensor.device`



In [27]:
# Default datatype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # float32, float16 (bit)
                               device=None, # cpu, gpu
                               requires_grad=False) # gradient descent
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Tensor operation

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication



In [30]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [31]:
tensor + 10

tensor([11, 12, 13])

In [32]:
tensor - 10

tensor([-9, -8, -7])

In [33]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [34]:
tensor * 10

tensor([10, 20, 30])

## Matrix Multiplication

In [35]:
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [36]:
torch.matmul(MATRIX, MATRIX)

tensor([[121, 136],
        [153, 172]])

In [37]:
# 2x3 tensor
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
# 3x2 tensor
tensor2 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor1, tensor2

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1, 2],
         [3, 4],
         [5, 6]]))

In [38]:
# 2x2 tensor
# matmul or mm
torch.mm(tensor1, tensor2)

tensor([[22, 28],
        [49, 64]])

### Transpose

In [39]:
tensor1 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensor2 = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

In [40]:
tensor2, tensor2.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 3, 5],
         [2, 4, 6]]))

In [41]:
tensor2.shape, tensor2.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [42]:
torch.mm(tensor1,tensor2.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

## min, max, mean, sum, and etc (tensor aggregation)

In [46]:
x = torch.arange(0,100,5)
x

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [47]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [48]:
torch.max(x), x.max()

(tensor(95), tensor(95))

In [50]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(47.5000), tensor(47.5000))